/** @type {import('stylelint').Config} */
export default {
    extends: 'stylelint-config-standard',
    plugins: ['@stylistic/stylelint-plugin', 'stylelint-order'],
    rules  : {
        'at-rule-empty-line-before': [
            'always',
            {
                ignore: [
                    'after-comment',
                    'first-nested',
                ],
                ignoreAtRules: [
                    'if',
                    'else',
                ],
            },
        ],
        'at-rule-no-unknown': null,
        'block-no-empty'    : true,
        'color-named'       : [
            'never',
            {
                ignore: [
                    'inside-function',
                ],
            },
        ],
        'color-no-invalid-hex'     : true,
        'comment-empty-line-before': [
            'always',
            {
                except: [
                    'first-nested',
                ],
                ignore: [
                    'after-comment',
                    'stylelint-commands',
                ],
            },
        ],
        'comment-no-empty'                         : true,
        'custom-property-empty-line-before'        : 'never',
        'custom-property-pattern'                  : 'v-.+',
        'declaration-block-no-duplicate-properties': [
            true,
            {
                ignoreProperties: [
                    'color',
                    '/background/',
                    '/padding-/',
                ],
            },
        ],
        'declaration-block-no-shorthand-property-overrides' : true,
        'declaration-block-no-redundant-longhand-properties': true,
        'declaration-empty-line-before'                     : 'never',
        'font-family-name-quotes'                           : 'always-where-recommended',
        'font-family-no-duplicate-names'                    : true,
        'font-family-no-missing-generic-family-keyword'     : true,
        'font-weight-notation'                              : 'numeric',
        'function-calc-no-unspaced-operator'                : true,
        'function-linear-gradient-no-nonstandard-direction' : true,
        'function-no-unknown'                               : [
            true,
            {
                ignoreFunctions: [
                    'constant',
                ],
            },
        ],
        'function-url-no-scheme-relative'    : true,
        'function-url-quotes'                : 'always',
        'keyframe-declaration-no-important'  : true,
        'lightness-notation'                 : 'number',
        'max-nesting-depth'                  : 20,
        'media-feature-name-no-unknown'      : true,
        'no-duplicate-at-import-rules'       : true,
        'no-duplicate-selectors'             : true,
        'no-empty-source'                    : true,
        'no-invalid-double-slash-comments'   : true,
        'no-unknown-animations'              : true,
        'number-max-precision'               : 4,
        'order/properties-alphabetical-order': null,
        'order/properties-order'             : [
            'background',
            'background-color',
            'background-image',
            'background-origin',
            'background-position',
            'background-repeat',
            'background-size',
            'border',
            'border-width',
            'border-style',
            'border-color',
            'border-top',
            'border-right',
            'border-bottom',
            'border-left',
            'border-top-width',
            'border-top-style',
            'border-top-color',
            'border-right-width',
            'border-right-style',
            'border-right-color',
            'border-bottom-width',
            'border-bottom-style',
            'border-bottom-color',
            'border-left-width',
            'border-left-style',
            'border-left-color',
            'border-radius',
            'border-top-left-radius',
            'border-top-right-radius',
            'border-bottom-right-radius',
            'border-bottom-left-radius',
            'box-shadow',
            'box-sizing',
            'color',
            'font',
            'font-size',
            'font-style',
            'font-weight',
            'line-height',
            'text-align',
            'text-decoration',
            'content',
            'cursor',
            'pointer-events',
            'user-select',
            'flex',
            'display',
            'align-items',
            'justify-content',
            'flex-direction',
            'flex-wrap',
            'order',
            'margin',
            'margin-top',
            'margin-right',
            'margin-bottom',
            'margin-left',
            'padding',
            'padding-top',
            'padding-right',
            'padding-bottom',
            'padding-left',
            'height',
            'min-height',
            'max-height',
            'width',
            'min-width',
            'max-width',
            'overflow',
            'overflow-x',
            'overflow-y',
            'position',
            'left',
            'top',
            'right',
            'bottom',
            'z-index',
            'filter',
            'opacity',
            'animation',
            'transform',
            'transition',
        ],
        'property-no-unknown'   : true,
        'rule-empty-line-before': [
            'always-multi-line',
            {
                except: [
                    'after-single-line-comment',
                    'first-nested',
                ],
                ignore: [
                    'after-comment',
                    'first-nested',
                ],
            },
        ],
        'selector-attribute-quotes': 'always',
        'selector-class-pattern'   : [
            '(?!\\.dp__)[a-z]+',
            {
                resolveNestedSelectors: true,
            },
        ],
        'selector-max-attribute'         : 2,
        'selector-max-class'             : 20,
        'selector-max-combinators'       : 20,
        'selector-max-compound-selectors': 20,
        'selector-max-id'                : 1,
        'selector-max-specificity'       : '1,10,1',
        'selector-max-type'              : 10,
        'selector-max-universal'         : 1,
        'selector-no-qualifying-type'    : [
            true,
            {
                ignore: [
                    'attribute',
                ],
            },
        ],
        'selector-pseudo-class-no-unknown': [
            true,
            {
                ignorePseudoClasses: [
                    'deep',
                ],
            },
        ],
        'selector-pseudo-element-no-unknown'    : true,
        'selector-type-no-unknown'              : true,
        'shorthand-property-no-redundant-values': true,
        'string-no-newline'                     : true,
        'time-min-milliseconds'                 : 100,
        'unit-no-unknown'                       : true,
        'value-no-vendor-prefix'                : true,
    },
    overrides: [
        {
            files       : ['*.scss', '**/*.scss'],
            extends     : 'stylelint-config-standard-scss',
            plugins     : ['stylelint-scss', '@stylistic/stylelint-plugin'],
            customSyntax: 'postcss-scss',
            rules       : {
                'scss/at-rule-no-unknown'     : true,
                'scss/dollar-variable-pattern': '^[_]?[a-z]+([a-z0-9-]+[a-z0-9]+)?$',
            },
        },
        {
            files       : ['*.html', '**/*.html'],
            extends     : 'stylelint-config-html',
            customSyntax: 'postcss-html',
            plugins     : ['@stylistic/stylelint-plugin'],
        },
        {
            files  : ['*.vue', '**/*.vue'],
            extends: ['stylelint-config-standard-vue', 'stylelint-config-recommended-vue', 'stylelint-config-recommended-vue/scss'],
            plugins: ['@stylistic/stylelint-plugin'],
            rules  : {
                '@stylistic/at-rule-name-space-after'        : 'always',
                '@stylistic/block-opening-brace-space-before': 'always',
                '@stylistic/indentation'                     : [
                    4,
                    {
                        baseIndentLevel: 1,
                    },
                ],
                '@stylistic/selector-combinator-space-after' : 'always',
                '@stylistic/selector-combinator-space-before': 'always',
            },
        },
    ],
    ignoreFiles: ['dist/**/*'],
};
