/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Home': RouteRecordInfo<
      'Home',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '404': RouteRecordInfo<
      '404',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    'About': RouteRecordInfo<
      'About',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'DynamicComponent': RouteRecordInfo<
      'DynamicComponent',
      '/dynamicComponent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'DefaultDynamicComponent': RouteRecordInfo<
      'DefaultDynamicComponent',
      '/dynamicComponent/defaultDynamicComponent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'InSuspense': RouteRecordInfo<
      'InSuspense',
      '/dynamicComponent/inSuspense',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Game': RouteRecordInfo<
      'Game',
      '/game',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'PhaserGame': RouteRecordInfo<
      'PhaserGame',
      '/game/phaserGame',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'WheelGame': RouteRecordInfo<
      'WheelGame',
      '/game/wheelGame',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'WheelGame2': RouteRecordInfo<
      'WheelGame2',
      '/game/wheelGame2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Suspense': RouteRecordInfo<
      'Suspense',
      '/suspense',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SuspenseAsyncComponent': RouteRecordInfo<
      'SuspenseAsyncComponent',
      '/suspense/asyncComponent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SuspenseAsyncData': RouteRecordInfo<
      'SuspenseAsyncData',
      '/suspense/asyncData',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'Home'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '404'
      views:
        | never
    }
    'src/pages/about/index.vue': {
      routes:
        | 'About'
      views:
        | never
    }
    'src/pages/dynamicComponent/index.vue': {
      routes:
        | 'DynamicComponent'
      views:
        | never
    }
    'src/pages/dynamicComponent/defaultDynamicComponent.vue': {
      routes:
        | 'DefaultDynamicComponent'
      views:
        | never
    }
    'src/pages/dynamicComponent/inSuspense.vue': {
      routes:
        | 'InSuspense'
      views:
        | never
    }
    'src/pages/game/index.vue': {
      routes:
        | 'Game'
      views:
        | never
    }
    'src/pages/game/phaserGame.vue': {
      routes:
        | 'PhaserGame'
      views:
        | never
    }
    'src/pages/game/wheelGame.vue': {
      routes:
        | 'WheelGame'
      views:
        | never
    }
    'src/pages/game/wheelGame2.vue': {
      routes:
        | 'WheelGame2'
      views:
        | never
    }
    'src/pages/suspense/index.vue': {
      routes:
        | 'Suspense'
      views:
        | never
    }
    'src/pages/suspense/asyncComponent.vue': {
      routes:
        | 'SuspenseAsyncComponent'
      views:
        | never
    }
    'src/pages/suspense/asyncData.vue': {
      routes:
        | 'SuspenseAsyncData'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
